apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
spec:
  replica: 1 
  template:
    metadata:
      labels:
        app: {{ template "fullname" $ }}
    spec:
      containers:
        {{- range .Values.sfNodes }}
        - name: {{ . }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env: 
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBELET_PORT
              value: "10250"
            - name: VKUBELET_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["virtual-kubelet"]
          args: ["--provider", "sf", "--namespace", "default", "--nodename", {{ . | quote }} , "--os", {{ default "Linux" $.Values.env.nodeOsType | quote }}, "--taint", {{ default "azure.com/sf" $.Values.env.nodeTaint | quote }}]
        {{- end }}
